name: Get YouTube Live m3u8
on:
  schedule:
    - cron: '0 0/3 * * *'

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: config
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    - name: Install yt-dlp
      run: |
        sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        sudo chmod a+rx /usr/local/bin/yt-dlp
        # j1东京新宿	
    - name: Get j1.m3u8
      run: |
        touch ./j1.m3u8
        sudo cat >./j1.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=DjdUEyjx8GM)
        EOL
        # j2 恵比寿駅前
    - name: Get j2.m3u8
      run: |
        touch ./j2.m3u8
        sudo cat >./j2.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=LR7i5_pkJBg)
        EOL
        # j3 東京六本木
    - name: Get j3.m3u8
      run: |
        touch ./j3.m3u8
        sudo cat >./j3.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=Uf2iLWzBpUI)
        EOL
        # j4 東京新宿歌舞伎町
    - name: Get j4.m3u8
      run: |
        touch ./j4.m3u8
        sudo cat >./j4.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=gFRtAAmiFbE)
        EOL
        # j5静岡市さった峠
    - name: Get j5.m3u8
      run: |
        touch ./j5.m3u8
        sudo cat >./j5.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=oHci2QFaRZs)
        EOL
        # j6 静岡市富士山
    - name: Get j6.m3u8
      run: |
        touch ./j6.m3u8
        sudo cat >./j6.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=OrGQEkkEkx4)
        EOL		
        # j7 富士山
    - name: Get j7.m3u8
      run: |
        touch ./j7.m3u8
        sudo cat >./j7.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=h6Z9v-qqHl8)
        EOL
        # j8 富士山山中湖高台
    - name: Get j8.m3u8
      run: |
        touch ./j8.m3u8
        sudo cat >./j8.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=87929IvGa-8)
        EOL
        # j9 富士山河口湖
    - name: Get j9.m3u8
      run: |
        touch ./j9.m3u8
        sudo cat >./j9.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=Sv9hcJ3k5h4)
        EOL
        # j10 富士本栖湖
    - name: Get j10.m3u8
      run: |
        touch ./j10.m3u8
        sudo cat >./j10.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=SThyjXJ6xC4)
        EOL		
        # j11 富士山中伊豆
    - name: Get j11.m3u8
      run: |
        touch ./j11.m3u8
        sudo cat >./j11.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=q5T3DxdzLs0)
        EOL	
        # j12 富士山精進湖
    - name: Get j12.m3u8
      run: |
        touch ./j12.m3u8
        sudo cat >./j12.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=xzyCWsc-wJE)
        EOL			
        # j13 函館山
    - name: Get j12.m3u8
      run: |
        touch ./j13.m3u8
        sudo cat >./j13.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=Q1oSzjYcV9w)
        EOL  
        # j14厳島神社の大鳥居	
    - name: Get j14.m3u8
      run: |
        touch ./j14.m3u8
        sudo cat >./j14.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=LNiKVMGkEiM)
        EOL
        # j15 西武新宿駅
    - name: Get j15.m3u8
      run: |
        touch ./j15.m3u8
        sudo cat >./j15.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=lA6TaaMGgDo)
        EOL 
        # j16大阪道頓堀	
    - name: Get j16.m3u8
      run: |
        touch ./j16.m3u8
        sudo cat >./j16.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=4Ek_1UULqq8)
        EOL
        # j17 熱海
    - name: Get j17.m3u8
      run: |
        touch ./j17.m3u8
        sudo cat >./j17.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=AyD6fzns6u8)
        EOL
        # j18 能登鹿島駅
    - name: Get j18.m3u8
      run: |
        touch ./j18.m3u8
        sudo cat >./j18.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=25600000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=THy9p2xJSek)
        EOL 
        # j19 津山城（鶴山公園）
    - name: Get j19.m3u8
      run: |
        touch ./j19.m3u8
        sudo cat >./j19.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=YQMk-L2RPwc)
        EOL 
        # j20 日本平夢
    - name: Get j20.m3u8
      run: |
        touch ./j20.m3u8
        sudo cat >./j20.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=2d0yO_QN1Iw)
        EOL	
        # j21 北九州市
    - name: Get j21.m3u8
      run: |
        touch ./j21.m3u8
        sudo cat >./j21.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=8UmtKvBz8vg)
        EOL 
        # j22 羽田空港
    - name: Get j22.m3u8
      run: |
        touch ./j22.m3u8
        sudo cat >./j22.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=bHQPi9K-1LU)
        EOL 
        # j23 国立天文台
    - name: Get j23.m3u8
      run: |
        touch ./j23.m3u8
        sudo cat >./j23.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=gm-57AcpZhQ)
        EOL		
        # j24 大阪国際空港
    - name: Get j24.m3u8
      run: |
        touch ./j24.m3u8
        sudo cat >./j24.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=QUCq3tBoyK8)
        EOL		
        # j25 博多駅
    - name: Get j25.m3u8
      run: |
        touch ./j25.m3u8
        sudo cat >./j25.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=bHRaXxyvgU0)
        EOL	
    - name: git add
      run: |
        git add -A
        ls -la
    - name: commit & push
      run: |
        git commit -m "links are updated"
        git push
